site_name: "Pacti"
site_description: "Compositional system analysis and design using contracts."
site_url: "https://FormalSystems.github.io/pacti"
repo_url: "https://github.com/FormalSystems/pacti"
repo_name: ""
site_dir: "site"
watch: [README.md, CONTRIBUTING.md, CHANGELOG.md, src/pacti]

nav:
- Home:
  - Overview: index.md
  - Installing: installing.md
  - Getting Started: getting_started.ipynb
  - Changelog: changelog.md
  - Credits: credits.md
  - License: license.md
# defer to gen-files + literate-nav
- Case Studies:
  - Overview: case_studies.md
  - Autonomous Systems: _case_studies/evaluating_perception/evaluating_perception.ipynb
  - Multi-agent Coordination: _case_studies/multiagent_coordination/multiagent.ipynb
  - Signal Processing in Digital ICs: _case_studies/digital_signal_processing/dsp_wl.ipynb
  - Synthetic Biology: _case_studies/biocircuit_specifications/specification_based_synthetic_biology.ipynb
  - Space Mission Scenario: 
    - Overview: _case_studies/space_mission/space_mission.ipynb
    - Power Viewpoint: _case_studies/space_mission/space_mission_power.ipynb
    - Science & Communication Viewpoint: _case_studies/space_mission/space_mission_science.ipynb
    - Navigation Viewpoint: _case_studies/space_mission/space_mission_navigation.ipynb
    - Thermal Viewpoint: _case_studies/space_mission/space_mission_thermal.ipynb
    - Schedulability Analysis with 3 Viewpoints: _case_studies/space_mission/space_mission_3viewpoints.ipynb
  - Mars 2020 Entry-Descent-Landing: _case_studies/mars_entry_descent_landing/mars_edl_2nd_encoding.ipynb
- API: #reference/
  - IoContract: iocontract.md
  - PolyhedralTerms : Polyhedral.md
- Development:
  - Contributing: contributing.md
  - Coverage report: coverage.md


theme:
  name: material
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
#  - toc.integrate
  icon:
    repo: fontawesome/brands/github
  font:
    #text: Eczar
    #text: Alegreya Sans
    #text: Roboto Slab
    #text: Inknut Antiqua
    text: Libre Baskerville
    #text: Cardo
    code: Roboto Mono
    #text: Merriweather
    #code: Inconsolata
  palette:
    scheme: default
    primary: white
    accent: purple
  logo: pacti_small_icon.svg
#  - media: "(prefers-color-scheme: light)"
#    scheme: default
#    primary: teal
#    accent: purple
#    toggle:
#      icon: material/weather-sunny
#      name: Switch to dark mode
#  - media: "(prefers-color-scheme: dark)"
#    scheme: slate
#    primary: black
#    accent: lime
#    toggle:
#      icon: material/weather-night
#      name: Switch to light mode

extra_css:
- css/material.css
- css/mkdocstrings.css

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - callouts
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist
  - toc:
      permalink: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
- search
- mkdocs-jupyter
- mkdocs-video
- markdown-exec
- gen-files:
    scripts:
    - docs/gen_ref_nav.py
- literate-nav:
    nav_file: SUMMARY.md
- coverage
- section-index
- mkdocstrings

extra:
  social:
  #- icon: fontawesome/brands/github
  #  link: https://github.com/FormalSystems
