on: [push,pull_request]

name: Test Action

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: pdm-project/setup-pdm@main
        name: Setup PDM
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ["x86", "x64"]
          enable-pep582: true
      - name: Install dependencies
        run: pdm install
      - name: Format code
        run: make format
      - name: Test code
        run: make test